<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyprograms" nsURI="platform:/plugin/tdt4250_Assignment1/model/studyprograms.ecore"
    nsPrefix="studyprograms">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="settingDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="University">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmes" upperBound="-1"
        eType="#//Programme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
        <details key="derivation" value="self.code + ' - '+ self.subject"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CourseCode"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//LevelType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="#//CourseCredit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="season" eType="#//SeasonType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degree" eType="#//DegreeType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisations" upperBound="-1"
        eType="#//Specialisation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childSpecialisations" upperBound="-1"
        eType="#//Specialisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseAllocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//CourseStatusType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroup" lowerBound="1"
        eType="#//CourseGroup" eOpposite="#//CourseGroup/courseAllocations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="validateSemesterCredits" value=" let mc = self.courseGroups ->collect(cg | cg.minRequiredCredits) -> sum()  in  (if mc >= 30.0 then true else false endif)"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="validateSemesterCredits"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterNumber" eType="#//SemesterNumber"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroups" upperBound="-1"
        eType="#//CourseGroup" containment="true" eOpposite="#//CourseGroup/semester"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="information" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="courseSeasonMatchesSemester"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//CourseGroupType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseAllocations" upperBound="-1"
        eType="#//CourseAllocation" containment="true" eOpposite="#//CourseAllocation/courseGroup"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRequiredCredits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" eType="#//Semester"
        eOpposite="#//Semester/courseGroups"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="information" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCredit" instanceClassName="float">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="maxInclusive" value="60"/>
      <details key="minInclusive" value="0"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="SemesterNumber" instanceClassName="int">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="minInclusive" value="1"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DegreeType">
    <eLiterals name="bachelor" literal="Bachelor"/>
    <eLiterals name="master" value="1" literal="Master"/>
    <eLiterals name="integratedMaster" value="2" literal="Integrert Master"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LevelType">
    <eLiterals name="foundationCourseLevel1" literal="Grunnleggende emner, nivaa 1"/>
    <eLiterals name="intermediateCourseLevel2" value="1" literal="Videregaaende emner, nivaa 2"/>
    <eLiterals name="thirdYearSubjectsLevel3" value="2" literal="Tredjeaarsemner, nivaa 3"/>
    <eLiterals name="secondDegree" value="3" literal="Hoyere grads nivaa"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseGroupType">
    <eLiterals name="mandatorySubjects" literal="Obligatoriske emner"/>
    <eLiterals name="electiveSubjects" value="1" literal="Valgbare emner"/>
    <eLiterals name="complimentarySubjects" value="2" literal="Komplementaere emner"/>
    <eLiterals name="engineeringSubjectsOtherProgramme" value="3" literal="Ingenioremne annet studieprogram"/>
    <eLiterals name="expertsInTeam" value="4" literal="Eksperter i Team"/>
    <eLiterals name="specialisationSubjectsThesis" value="5" literal="Fordypningsemner og masteroppgave"/>
    <eLiterals name="omradeemne" value="6" literal="Områdeemne"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseStatusType">
    <eLiterals name="O" literal="O"/>
    <eLiterals name="V" value="1"/>
    <eLiterals name="VA" value="2" literal="VA"/>
    <eLiterals name="VB" value="3" literal="VB"/>
    <eLiterals name="MAX1A" value="4" literal="MAX1A"/>
    <eLiterals name="M1A" value="5" literal="M1A"/>
    <eLiterals name="M2A" value="6" literal="M2A"/>
    <eLiterals name="M" value="7" literal="M"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SeasonType">
    <eLiterals name="fall" literal="Host"/>
    <eLiterals name="spring" value="1" literal="Vaar"/>
    <eLiterals name="both" value="2" literal="Begge"/>
  </eClassifiers>
</ecore:EPackage>
