<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyprograms" nsURI="platform:/plugin/tdt4250_Assignment1/model/studyprograms.ecore"
    nsPrefix="studyprograms">
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//CourseCode"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//LevelType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit" eType="#//CourseCredit"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="degree" eType="#//DegreeType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semesters" upperBound="-1"
        eType="#//Semester" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisations" upperBound="-1"
        eType="#//Specialisation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="childSpecialisations" eType="#//Specialisation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroups" eType="#//CourseGroup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="University">
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmes" upperBound="-1"
        eType="#//Programme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LevelType">
    <eLiterals name="foundationCourseLevel1" literal="foundation Course, Level1"/>
    <eLiterals name="intermediateCourseLevel2" value="1" literal="intermediate Course, Level2"/>
    <eLiterals name="thirdYearSubjectsLevel3" value="2" literal="third Year Subjects, Level3"/>
    <eLiterals name="secondDegree" value="3" literal="second degree"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DegreeType">
    <eLiterals name="bachelor" literal="bachelor"/>
    <eLiterals name="master" value="1"/>
    <eLiterals name="integratedMaster" value="2" literal="integrated master"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//CourseGroupType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesterNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroups" upperBound="-1"
        eType="#//CourseGroup" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroupAllocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseGroupType">
    <eLiterals name="mandatorySubject" literal="mandatory subject"/>
    <eLiterals name="complimentarySubject" value="1" literal="complimentary subject"/>
    <eLiterals name="optionalSubject" value="2" literal="optional subject"/>
    <eLiterals name="engineeringSubjectOtherProgramme" value="3" literal="engineering subject other programme"/>
    <eLiterals name="expertsInTeam" value="4" literal="experts in team"/>
    <eLiterals name="specialisationSubject" value="5" literal="specialisation subject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCode" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="CourseCredit" instanceClassName="float"/>
  <eClassifiers xsi:type="ecore:EClass" name="CourseGroupAllocation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisation" eType="#//Semester"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroup" eType="#//CourseGroup"/>
  </eClassifiers>
</ecore:EPackage>
